### ISSUE TITLE
NPM Advisory - BL - Remote Memory Exposure

### ISSUE THREAD

**Issue by goyney** [mafintosh/tar-stream#126]
The version of `bl` that is included in `tar-stream` (4.0.1) is affected by https://npmjs.com/advisories/1555. `bl` has released 4.0.3 which fixes this.

An update of `bl` to the latest would be appreciated to resolve this security vulnerability.

**Comment by goyney** [comment]
Looks like a PR already exists for this request: https://github.com/mafintosh/tar-stream/pull/125

**Comment by heyfirst** [comment]
+1 for this

**Comment by mafintosh** [comment]
Hi, 4.0.3 is already covered by the package.json
