### ISSUE TITLE
Leading slash is removed on long paths

### ISSUE THREAD

**Issue by lal12** [mafintosh/tar-stream#127]
I noticed that tar-stream removes the leading slash on long paths.

The problem is the splitting into name and prefix in headers.js. There a leading slash is dropped, because of line 208 where essentially `prefix = '' + name.slice(0,0)` is called which still is an empty string, but the first char is also dropped in name `name = name.slice(0 + 1)` 

I can do a PR, just wanted to know if there is any specific reason for this or if it is just a bug.

**Comment by clarkttfu** [comment]
@lal12 comment appreciated:
`prefix += prefix ? '/' + name.slice(0, i) : name.slice(0, i || 1)`
