### ISSUE TITLE
doesn't work with 

### ISSUE THREAD

**Issue by GreatEarl** [mafintosh/tar-stream#140]
I'm trying to use this with NestJS

I have an import on top and init this as 
`const pack = tar.pack()` 
inside async function.
and this line literally stops executing everything.

Any suggestions?

**Comment by mafintosh** [comment]
Doesn’t sound like a tar issue. That line just instantiates a stream

**Comment by GreatEarl** [comment]
@mafintosh thanks for the quick response, mate!
Can I give you a bit of a context?
I have a few files, all in memory those come as [{name: string, content: Buffer},{},{}...]
I trying to pack this array into one tarball and return as a stream so this tarball has the number of entries as the length of this array.
Can you give any ideas maybe?
 Thanks!
