### ISSUE TITLE
Missing fast-fifo dependency 

### ISSUE THREAD

**Issue by eliliam** [mafintosh/tar-stream#155]
It appears as a recent release has added in the use of the `fast-fifo` library, however this is not included in the `package.json` and is causing this module to fail when ran. This was noticed by updating the puppeteer version to 20.4.0 and above, which references a version of this package with this issue present.

https://github.com/mafintosh/tar-stream/blob/0490aeda616e666ea5b2bbc8758c8574fdb8d600/extract.js#L2

Please add `fast-fifo` to the dependencies to fix this.

**Comment by eliliam** [comment]
This PR fixes the issue
https://github.com/mafintosh/tar-stream/pull/156

**Comment by mafintosh** [comment]
3.1.4
