### ISSUE TITLE
create entry  with base-256 size

### ISSUE THREAD

**Issue by fbeauchamp** [mafintosh/tar-stream#160]
Hi, 

  We are using  `tar-stream`in our open source software  `xen-orchestra` . Tar stream support reading a size in base-256 format, but use the octal text format for writing an entry, silently limiting the size of each entry to 8.5GB, if not using pax header.  

  Our target tar consumer (virtual box)  does not support pax. Would it be ok to make a PR using base-256 size for entry, or make it optional and throwing an error if a size overflow ? 

Regards, 

Florent

**Comment by mafintosh** [comment]
Sure, if easy to maintain

**Comment by fbeauchamp** [comment]
Hi , 
   after re-reading the code I saw that I use an older version ( 2.x) , the current version already use base-256 encode for the size ( from here https://github.com/mafintosh/tar-stream/blob/master/headers.js#L73 )
 
    I am updating our code to handle the non node stream of the 3.x instead, and closing this issue.
   
Regards,
