### ISSUE TITLE
Modifying tar in place

### ISSUE THREAD

**Issue by Kequc** [mafintosh/tar-stream#41]
I perform tar file manipulation in my application. Adding, or replacing files in the tar archive. I built a wrapper that tries to keep it managed.

I'm manipulating tar files the way you suggest in the readme, by opening the tar, putting each entry into a new tar stream and writing that. However I don't really want a new tar file, so I've taken to moving the existing tar file to tmp (using fs.rename) and opening it from there. That way I can always just write to where the file is supposed to be.

It seems when I try to move a tar to tmp, while it is being accessed by tar-stream I receive an error. So, if two requests happen almost immediately after one another I get:

```
Error: ENOENT, rename '/<where-file-is-supposed-to-be>.tar'
    at Error (native)
```

At the fs.rename call.

What should I do about this? Is there a way to check whether a file operation is currently being performed?

Should I wait in that case using setTimeout?

```
    fs.rename(self.fullPath, tmpName, function (err) {
      if (err) {

        // TEMP: throw err
        throw err;
```

Is there a way to manipulate the tar file in place, without moving it? Wouldn't that just cause the same problem? I'm sorry if this is an easy question.

**Comment by LinusU** [comment]
`ENOENT` means one of two things in this case. Either the file you are trying to rename can't be find; or the directory in which you are trying to move the file to doesn't exist.

It shouldn't affect that you have already opened the file with `tar-stream`, but that could in some cases cause other problems.

I would suggest that you first move it with `fs.rename` and then, after the move is done, open it with `tar-stream`.

Keep in mind that moving to the temporary directory might be a costly operation if they are not on the same mounted volume. I would suggest keeping the file in the same folder and only renaming it.
