### ISSUE TITLE
Symlinks size is not consistent

### ISSUE THREAD

**Issue by piranna** [mafintosh/tar-stream#48]
There's different behaviour on the entry size field of symlinks when the location is set as stream or in the header, having sometimes a symlink with zero size and other times a symlink to nowhere but with a size the length of the destination path. It's needed to know what says the spec and make it work homoneneously.

**Comment by piranna** [comment]
According to http://bugs.python.org/issue1167128, gnu `tar` expects symlinks size to be zero, or it will throw a `skipping the next header` error. It seems this will be the source of issue #44. Fix will need to set explicitly size to zero somewhere between [these lines](https://github.com/mafintosh/tar-stream/blob/71439bf2df547900b4e098916042ddf294c11b17/pack.js#L138-L145).

**Comment by mafintosh** [comment]
Fixed in #54
