### ISSUE TITLE
pack.entry with streams

### ISSUE THREAD

**Issue by chpio** [mafintosh/tar-stream#49]
hi,

the pack.entry function only accepts buffers, but no streams. Im not really sure if this is even implementable. Any ideas about this?

**Comment by mafintosh** [comment]
It returns a writable stream you can pipe your own stream to if you dont pass a buffer

**Comment by chpio** [comment]
yeah, that's not what i meant by that. i was talking about the input: https://github.com/mafintosh/tar-stream/blob/33a55ac4749a60c6f1a070dc6d85dd68d871cc5b/pack.js#L128-L135

my workaround looks like this:
https://github.com/chpio/tar-vinyl/blob/e8dd48926b5719e7c4b99d7173c915b9ef0d0ad1/tar-vinyl.es2015.js#L45-L49

**Comment by mafintosh** [comment]
i'm still not sure what the problem is? why don't you just do

``` js
v.contents.pipe(this._tarPak.entry(header), cb)
```

**Comment by chpio** [comment]
ahh it will return an Sink object (which is Writable) if no buffer was passed... aha... i was focused to much on the buffer argument :(

Thank you for your help!
