### ISSUE TITLE
extract halts unexpectedly if predecessor stream is unzipped

### ISSUE THREAD

**Issue by chpio** [mafintosh/tar-stream#50]
hi,

i encountered a bug with this package:
- if used with `gunzip-maybe` or `zlib.createGunzip()` the output stops after a few file entries
- if the content is pre-unzipped (the same tar.gz file stored uncompressed) everything goes well
- if the stream is consumed in the `extract.on('entry')` handler everything goes well

https://gist.github.com/chpio/6d0cedae59d8416d0aed

ohh, i don't know if it's relevant, i noticed the stops occur after a large file entry.

**Comment by chpio** [comment]
ohh, i don't know if it's relevant, i noticed the stops occur after a large file entry.

**Comment by mafintosh** [comment]
you need to resume the content stream or pipe it somewhere

```
.on('entry', function (header, stream, next) {
  stream.resume()
  next()
})
```

**Comment by chpio** [comment]
ok, so the usage of the stream outside of the entry handler is unsupported? like passing it into another stream and consume it later?

**Comment by mafintosh** [comment]
no thats fully supported as long as you drain the stream at some point.

**Comment by chpio** [comment]
hmm, yeah, the problem is that "later"/"at some point" is never called if the stream is not consumed "early"

**Comment by mafintosh** [comment]
i'm not sure what you mean
