### ISSUE TITLE
large file issue

### ISSUE THREAD

**Issue by bobzoller** [mafintosh/tar-stream#61]
I've got a tar file with a few large (>10GB) files in it.  When tar-stream gets to the first big file, it chokes with an `Invalid tar header` error.  I can't provide the tar file itself, but hopefully this is helpful:

it hums along through a few small files, and then it hits the header for the first large file (provided here base64 encoded):

```
cnMtZHMwNTk1NDhfMjAxNi0xMS0yOFQxOTAwMTEuMDAwWi9nb29kZWdncy1nYXJiYW56by9vcmRlcl9pdGVtcy5ic29uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDA2NDQAMDAwMTc1MQAwMDAxNzUxAIAAAAAAAAACfZ6FHjEzMDE3MTAxMDc1ADAyMzMxNgAgMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1c3RhciAgAG1hZG1pbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYWRtaW5zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
```

which it claims to parse and tells me is `{name: 'rs-ds059548_2016-11-28T190011.000Z/goodeggs-garbanzo/order_items.bson', size: 2}` ... but the size according to bsdtar on OSX is `10697475358` ...

and then it chokes parsing the next tar header (presumably because it has used the entirely wrong offset).

If I can provide more data (without providing the file itself), please let me know.

**Comment by piranna** [comment]
Tar format is not so standard as we would love... ;-) and there are some differences on the implementations. So far I think tar-stream try to follow gnu tar format and behaviour (common on linux systems). Have you been able to read your file using it? I think gnu tar can be installed on OSX using brew or some any other tool...

**Comment by bobzoller** [comment]
Yes, gnutar 1.28 reports the correct size under OSX.

**Comment by piranna** [comment]
Have you needed to use any special flag? If not, could you be able to confirm if there's any difference in the formats? If so, maybe gnutar is detecting it...

**Comment by bobzoller** [comment]
no special flags on the consuming end.  I'm not sure about the producing end -- this tarfile is created by a thirdparty.

not sure what you mean about difference in the formats...

**Comment by piranna** [comment]
https://bbs.archlinux.org/viewtopic.php?pid=1140189#p1140189

Seems bsdtar support extended attributes, while gnu tar didn't, not sure now. Maybe we are not supporting either at this moment...

**Comment by bobzoller** [comment]
the `typeflag` for this header is `57`, which does not appear to be handled by tar-stream.  I guess this is pax interchange format?  https://www.freebsd.org/cgi/man.cgi?query=tar&sektion=5
