### ISSUE TITLE
Sparse file support?

### ISSUE THREAD

**Issue by erth64net** [mafintosh/tar-stream#63]
It appears that your streaming tar parser does not support sparse files. Am I mistaken?

It it helps, GNU tar implements sparse support at:
http://git.savannah.gnu.org/cgit/tar.git/tree/src/sparse.c?id=63f2e969ddc162da7ae49a955bba9c6a2a0e77dc#n354

My question is relevant to this:
 http://stackoverflow.com/questions/40166300/cross-platform-sparse-file-compression-with-nodejs

Also poking at cpio-stream for sparse support options too: https://github.com/finnp/cpio-stream/issues/9

**Comment by piranna** [comment]
Do you get any error/exception when working with sparse files? Could you be able to provide an example or a test that we could work with? The same for sparse cpio files (I'm not a maintainer, but I'm watching both repos :-) ).

**Comment by erth64net** [comment]
Best to create/replicate on the same machine. Creation of sparse files is easy enough: https://wiki.archlinux.org/index.php/sparse_file

**Comment by piranna** [comment]
What you have showed is hos to create a sparse file at filesystem level, not on a tarfile. Anyway, what we need is to know how they are identified in the tar metadata. Can you probide us some docs about where a sparse file is identified in the tar header?

**Comment by maxogden** [comment]
Yes, a reproducible test case would be helpful

**Comment by erth64net** [comment]
I'm a little confused by the requests, but hopefully this helps:
`
~$ truncate -s 512M file.img
~$ tar cvzfS file.tar file.img
file.img
~$ du -h file.img
0	file.img
~$ du -h --apparent-size file.img
512M	file.img
~$ ls -l
total 4
-rw-r--r-- 1 gregg gregg 536870912 Dec  3 15:42 file.img
-rw-r--r-- 1 gregg gregg       127 Dec  3 15:42 file.tar
`

When extracting without sparse support, or when capturing without sparse support, the extracted file would appear instead as:
`
~$ du -h file.img
512M	file.img
`

As for how to identify a sparse file, it looks like GNU tar's sparse.c file gets into those details about halfway though: http://git.savannah.gnu.org/cgit/tar.git/tree/src/sparse.c

**Comment by piranna** [comment]
I have searched a bit about the tar sparse and seems there are three different file header formats, being the two oldest ones incompatible with posix extensions, and the third one seems to be only compatible with the pax tar format. What should we use? Seems tar-stream only implement ustar, that's the most extended one...

**Comment by mafintosh** [comment]
might add this in the future

**Comment by mafintosh** [comment]
we support pax now
