### ISSUE TITLE
8GB Limit?

### ISSUE THREAD

**Issue by dandanknight** [mafintosh/tar-stream#75]
Can you confirm (or not) that there is an 8GB limit (per file) for TAR creation with the implementation of TAR that you use (ustar is it?)

If so, is there any way round this that you know of? Or another library i could use?

Many thanks

**Comment by diamondap** [comment]
You **can** add files larger than 8GB into a tar archive with this library using pax headers. It just wasn't documented. See the code snippet at https://github.com/mafintosh/tar-stream/pull/78.

**Comment by piranna** [comment]
Maybe it would be good to add it to a FAQ section in the readme.
