### ISSUE TITLE
Buffer constructor runtime deprecation - this package emits a warning on Node 10

### ISSUE THREAD

**Issue by benjamingr** [mafintosh/tar-stream#79]
Hey from Node.js here!, 

Starting on Node 10 this package will emit deprecation warnings.  See [this guide](https://github.com/ChALkeR/safer-buffer/blob/master/Porting-Buffer.md) on what you should do in order to migrate to `Buffer.alloc`/`Buffer.from`. 

See https://github.com/nodejs/node/issues/19079 for discussion around this change and why we can't make `new Buffer` work

**Comment by mafintosh** [comment]
You wanna PR a fix?

**Comment by benjamingr** [comment]
@mafintosh done, though there is no contributing.md or building.md so please validate that my changes are on par with your policy and I didn't break anything :)

**Comment by felixrabe** [comment]
As a workaround for now, I've created a `~/bin/node` script that comes before (Homebrew-installed) `/usr/local/bin/node` in my `$PATH`:

    #!/bin/bash

    /usr/local/bin/node --no-deprecation "$@"

**Comment by mafintosh** [comment]
Should be fixed. There was some deps that needed updating as well :/
