### ISSUE TITLE
Fails to extract  an archive  with GBK characters in file names !

### ISSUE THREAD

**Issue by alenhu** [mafintosh/tar-stream#94]
I change headers.js 。
var iconvl = require('iconv-lite');
var UTF8 = require('utf-8');
var decodeStr = function (val, offset, length, encoding) {
  var tmp = val.slice(offset, indexOf(val, 0, offset, offset + length));
  if(UTF8.isNotUTF8(tmp)){
    return iconvl.decode(tmp,'GBK').toString();
  }else{
    return tmp.toString();
  }
}

**Comment by mafintosh** [comment]
if still revelant send a test case
