### ISSUE TITLE
PR for typescript definition?

### ISSUE THREAD

**Issue by alvis** [mafintosh/tar-stream#97]
@mafintosh: Do you accept a typescript definition PR for tar-stream?
I have one working at https://github.com/alvis/tar-stream/tree/typescript

It would be great if the definition is attached at the source, as any incompatible change can be detected by the test.
But I'm aware that some authors prefer not to have the definitions attached at the source. If it's the case, I'd submit it to DefinitelyTyped instead.

**Comment by mafintosh** [comment]
What do I need to do to help you support this?

**Comment by alvis** [comment]
nothing. I've got everything working and tested. :)

**Comment by alvis** [comment]
ping @mafintosh: happy to accept a PR?

**Comment by mafintosh** [comment]
feel free to pr typings if relevant
